### PR TITLE
Module Initialization. Added code quality tools.

### PR DESCRIPTION
**Pull request by pkornowski**

### CODE REVIEW

**Comment by pkornowski** [comment]
@areklalo 
Looks good to me.

**Comment by dkayiwa** [comment]
@pkornowski @areklalo  a pull request with lots of merge commits is hard to review. Can you ensure that you have the latest upstream changes before creating one?

**Comment by pkornowski** [comment]
@dkayiwa 
Yes, we can. These merges were caused because we didn't have the repository on the OpenMRS yet.

**Comment by dkayiwa** [comment]
Oh i see! 😊

**Pull request merged**
