### PR TITLE
SYNCT-93: Fixed filtering by operations

### PR DESCRIPTION
**Pull request by taher44**
[SYNCT-93: Fix filtering by operation](https://issues.openmrs.org/browse/SYNCT-93)

### CODE REVIEW

**Comment by dkayiwa** [comment]
@pkornowski what do you think of this?

**Comment by dserkowski** [comment]
@pkornowski is unavailable. I will review it.

**Comment by dserkowski** [comment]
It looks ok. @taher44, could you change also this exception message (action -> operation)? https://github.com/openmrs/openmrs-module-sync2/blob/0d2d47c2a9aa9f94f5529a93bfa28b22d0816fa6/omod/src/main/java/org/openmrs/module/sync2/web/controller/rest/SyncAuditRestController.java#L178

**Comment by dserkowski** [comment]
@dkayiwa, can you merge this?

**Comment by dkayiwa** [comment]
@dserkowski i have merged it. But can give you necessary permissions if you need to merge more. 😊

**Pull request merged**
