### PR TITLE
SYNCT-292 - Unable to sync a patient with a person attribute type value that is an instance of an Attributable type

### PR DESCRIPTION
**Pull request by wluyima**
https://issues.openmrs.org/browse/SYNCT-292

### CODE REVIEW

**Comment by dkayiwa** [comment]
@wluyima did you see the travis build failure?

**Comment by areklalo** [comment]
@wluyima 
Thanks a lot for your work. 
I see there missing dependency of com.fasterxml.jackson.core
```
java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonSetter
```
Please try to add this to the omod/pom.xml.
```
<dependency>
  <groupId>com.fasterxml.jackson.core</groupId>
  <artifactId>jackson-databind</artifactId>
  <version>2.9.7</version>
  <scope>test</scope>
</dependency>
```
That should fix the build failure.

**Comment by wluyima** [comment]
I doubt, there is something strange with this, I think the issue is because it's is a duplicate dependency and not a missing one which I removed [here](https://github.com/openmrs/openmrs-module-sync2/commit/7970e4a2e191123281502721fbcb4e98eb1abb1a), I think I should have excluded it in the api subproject too

**Comment by wluyima** [comment]
@areklalo you were right, but I also had to remove other duplicate dependencies in master

**Comment by areklalo** [comment]
@wluyima 
Thank's for your investigation. The code looks good, thanks.

**Pull request merged**
